---
EnableDefaultLinters: false
linters:
  TrailingWhitespace:
    enabled: true
  FinalNewline:
    enabled: true
  SpaceAroundErbTag:
    enabled: true
  ExtraNewline:
    enabled: true
  SpaceIndentation:
    enabled: true
  RightTrim:
    enabled: true
  ClosingErbTagIndent:
    enabled: true
  CommentSyntax:
    enabled: true
